# Generated by Django 5.0.6 on 2024-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMedico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=1)),
                ('texture', models.FloatField()),
                ('perimeter', models.FloatField()),
            ],
        ),
    ]
