# Generated by Django 5.0.6 on 2024-06-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histogramas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportemedico',
            old_name='diagnosis',
            new_name='Diagnosis',
        ),
        migrations.RenameField(
            model_name='reportemedico',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='reportemedico',
            old_name='perimeter',
            new_name='Perimeter',
        ),
        migrations.RenameField(
            model_name='reportemedico',
            old_name='texture',
            new_name='Texture',
        ),
    ]
