# Generated by Django 5.0.6 on 2024-06-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histogramas', '0002_rename_diagnosis_reportemedico_diagnosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportemedico',
            old_name='Perimeter',
            new_name='Perimetro',
        ),
        migrations.RenameField(
            model_name='reportemedico',
            old_name='Texture',
            new_name='Textura',
        ),
    ]
