# Generated by Django 5.0.6 on 2024-06-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histogramas", "0003_rename_perimeter_reportemedico_perimetro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportemedico",
            name="Radio",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
